Context state setup
WildbookOrg/report-app pull request #27
Opened 2020-10-26 23:57 UTC by robinsph21

Purpose:
Add in React Context and start separating out elements into state.

Changes:
Moved sighting cards to `/src/context/storage.js` as external storage
Added context provider at the top level of the app

Testing:
Tested on Android.

**Screenshots:**
N/A

2020-10-27 00:17 UTC, dborg291 approved these changes

2020-10-27 21:21 UTC, brmscheiner requested changes

2020-10-27 21:21 UTC, brmscheiner commented on src/context/report-context.jsx
> +      break;
two things
1. make sure your code is linted before merging 
2. consider using the built-in functions map, filter and reduce instead of for loops - you will find far fewer errors and more readable code. for example this one would be 

```
state.sightings.filter(sighting => sighting.id !== action.targetID)
```

2020-10-27 21:21 UTC, brmscheiner commented on src/context/report-context.jsx
> +
this function does not return the new state (nothing would happen)

2020-10-27 21:21 UTC, brmscheiner commented on src/context/storage.js
> +      image: require('../../assets/jaguar.jpg'),
we are using imports not requires

2020-10-27 23:39 UTC, robinsph21 commented on src/context/report-context.jsx
> +      break;
Noted, I did forget to set up linting.

And yes. That makes more sense. I was just throwing code in there instead of leaving it blank for PR's sake, but I will change that.

2020-10-27 23:40 UTC, robinsph21 commented on src/context/storage.js
> +      image: require('../../assets/jaguar.jpg'),
The way I understand it currently, you can't import an image inside a Javascript object. So we would have to know beforehand which images we want to import, which won't be the case for the app I feel. Is there something I am missing? How important is require vs import?

2020-10-28 01:55 UTC, brmscheiner commented on src/context/storage.js
> +      image: require('../../assets/jaguar.jpg'),
Ahhh yes I think this is a confusing point. By not being able to import inside of an object, it only means you have to do it at the top of the file. So here it would be 

```
import img1 from '../../assets/elephant.jpg';
import img2 from '../../assets/jaguar.jpg';

...

export default storage = {
  sightings: [
    {
      id: 1,
      image: img1,
      name: 'Humpback Whale',
      date: 'September 23rd, 2019',
      synced: true,
      inProgress: false,
    },
    {
      id: 2,
      image: img2,
      name: 'Anna\'s Hummingbird',
      date: 'September 23rd, 2019',
      synced: true,
      inProgress: false,
    },
```

There's actually more here than meets the eye, whether we use requires or imports. Webpack uses a module called file loader to create URLs for the images and hands it off to you.

2020-10-28 01:56 UTC, brmscheiner commented on src/context/storage.js
> +      image: require('../../assets/jaguar.jpg'),
here's a link to that if you're curious: https://webpack.js.org/loaders/file-loader/

2020-10-28 04:10 UTC, robinsph21 commented on src/context/storage.js
> +      image: require('../../assets/jaguar.jpg'),
I guess I just balked at adding an import statement from a state function programmatically. Sure I can write that in by hand, but how to do that with the code. Hopefully webpack clears it up..

2020-10-28 06:45 UTC, robinsph21 commented on src/context/storage.js
> +      image: require('../../assets/jaguar.jpg'),
https://stackoverflow.com/questions/42118296/dynamically-import-images-from-a-directory-using-webpack#_=_ This post echoes my concern. What do you think of the solution posed/how to address this in the future?

2020-10-28 08:30 UTC, brmscheiner commented on src/context/storage.js
> +      image: require('../../assets/jaguar.jpg'),
Ahh, I see now. Yes, if it started to become a problem that `importAll` utility could be very handy

2020-10-28 08:32 UTC, robinsph21 commented on src/context/storage.js
> +      image: require('../../assets/jaguar.jpg'),
For now I've committed hardcoded values again, but I'm going to work on implementing the importAll utility (and learning a bit more about webpack, specifically the `require.context` function).

2020-10-29 21:52 UTC, merged